//! Tensor Products, as constructed in Atiyah-Macdonald

// ... need to implement first:
//
//           1. quotient module
//           2. free modules
//           3. submodules generated by elements
//
// (also need to learn how to use alga, which may be challenging, given the lack
//  of available documentation)
